# Generated by Django 3.1.6 on 2021-02-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sismologico', '0002_auto_20210214_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sismo',
            name='focalInfo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sismo',
            name='gapInfo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
