# Generated by Django 3.0.6 on 2021-04-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sismologico', '0006_auto_20210316_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='image_path',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
