# Generated by Django 3.1.6 on 2021-04-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sismologico', '0007_auto_20210410_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
